---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Check whether certificates defined in vhosts exist.
  stat: path={{ item.certificate_file }}
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts | bool

- name: Configure MPM module
  template:
    src: "00-mpm.conf.j2"
    dest: "{{ apache_modules_conf_path }}/00-mpm.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Comment modules not supported by MPM worker/event
  block:
    - name: php_module
      lineinfile:
        path: "{{apache_conf_path}}/php.conf"
        regexp: "^(php_value .*)"
        line: '#\1'
        backrefs: yes
      register: x
      until: not x.changed
      retries: 9999
      delay: 0
      ignore_errors: true
  when: apache_mpm_module == 'event' or apache_mpm_module == 'worker'


- name: Check if localhost cert exists (RHEL 8 and later).
  stat:
    path: /etc/pki/tls/certs/localhost.crt
  register: localhost_cert
  when: ansible_distribution_major_version | int >= 8

- name: Ensure httpd certs are installed (RHEL 8 and later).
  command: /usr/libexec/httpd-ssl-gencerts
  when:
    - ansible_distribution_major_version | int >= 8
    - not localhost_cert.stat.exists
